services:
  db:
    image: postgres:15
    container_name: fastapi_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fastapi_app
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      # Тут ми використовуємо змінні, які підставляться з вашого .env
      - DATABASE_URL=${DATABASE_URL}
      - PYTHONPATH=/code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

volumes:
  postgres_data: